kind: wasmer.io/App.v0
name: moshel-edibles
package: .

# 1. Inject the live database credentials into the environment variables
env:
  APP_ENV: "staging"
  APP_DEBUG: "true"
  DB_CONNECTION: "mysql"
  DB_HOST: "db.fr-roub1.bengt.wasmernet.com"
  DB_PORT: "20184"
  DB_DATABASE: "moshel"
  DB_USERNAME: "user_e30efcf9"
  DB_PASSWORD: "pw_zw9T5ceApv4P1FyydB0mwd30P6EBpliu"

# 2. Tell the builder to pass the --force flag to the automated migrations
build:
  commands:
    - php artisan migrate --force
