[package]
name = "Moshel Edibles"
version = "0.1.0"
description = "Laravel app on Wasmer"

[[deploy]]
[deploy.env]
APP_ENV = "staging"
APP_KEY = "base64:3DcjflCtTTEIhHVvykXywp2h7GJLomGrTrJRXHKT8bc="
APP_DEBUG = "true"

[deploy.build]
# This explicitly tells Wasmer to force migrations without prompting
commands = [
    "php artisan migrate --force",
    "php artisan config:cache",
    "php artisan route:cache"
]
