[package]
name = "moshel-edibles"
version = "0.1.0"

[[deploy]]
[deploy.env]
APP_ENV = "staging"
DB_CONNECTION = "mysql"
DB_HOST = "://wasmernet.com"
DB_PORT = "20184"
DB_DATABASE = "moshel"
DB_USERNAME = "user_e30efcf9"
DB_PASSWORD = "pw_zw9T5ceApv4P1FyydB0mwd30P6EBpliu"
