[package]
name = "moshel-edibles"
version = "0.1.0"

[[deploy]]
[deploy.env]
APP_ENV = "staging"
APP_DEBUG = "true"
DB_CONNECTION = "mysql"
# Wasmer will auto-inject DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD
